# Generated by Django 5.1.6 on 2025-02-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
